graph TD
Project{Git Project}-->Package{Python Package}
Project-->|defines file|SetupPy{setup.py}
Project-->Docs{Sphinx-based Documentation}
Docs-->|configured at|docs/conf.py
Package-->Module{Python Module}
Module-->TroveClassifiers{Trove Classifiers}
Package-->Namew
Package-->Short-Description
Project-->|has|README{README.rst}

SetupPy-->|describes|Package
SetupPy-->|provides|CLI{Command-line Script}